### ISSUE TITLE
Net framework quickstart: responding to SMS, incoming message is empty

### ISSUE THREAD

**Issue by BumpaRoy** [twilio-labs/twilio-aspnet#132]
I have followed the example to receive a response from an SMS using ASP.Net

    I have ngrok installed and working.
    My Console has been updated with URL from ngrok with \sms appended
    My asp app is running.
    I can debug code and get breakpoint in my SMSController class.
    But the incomingMessage.Body is Nothing

Using [vb.net](http://vb.net/) in my ASP app.

![local](https://github.com/twilio-labs/twilio-aspnet/assets/137801704/08df13ce-b805-419a-a62e-dcb8ef515190)
![HomeController code](https://github.com/twilio-labs/twilio-aspnet/assets/137801704/0992dada-4804-4fa8-9647-e87e84feda9d)
![SMSController code](https://github.com/twilio-labs/twilio-aspnet/assets/137801704/ae0dfb7b-d356-4188-9b29-f28dc51c7949)
![Create SMS Code](https://github.com/twilio-labs/twilio-aspnet/assets/137801704/7632c51b-b440-4e4b-9379-d4a8976ddb47)
![twilio Console](https://github.com/twilio-labs/twilio-aspnet/assets/137801704/b1175fbe-505b-4bee-b563-44ad0fb1b8c9)
![Ngrok](https://github.com/twilio-labs/twilio-aspnet/assets/137801704/7bece121-32c5-4d0f-bd0f-030aeb88c936)

**Comment by Swimburger** [comment]
I manually typed over your code and it works fine for me.
(share the code instead of screenshots next time 🙏)

Unfortunately, there's nothing else I can look into. I'd suggest checking your ngrok dashboard at http://127.0.0.1:4040/inspect/http and inspect the HTTP requests that Twilio sends to you.
Maybe you'll find something odd there to investigate.

**Comment by BumpaRoy** [comment]
First, thank you for the reply.  

I looked at the dash board and it is not sending back the body of the message.  I am trying to follow the example https://www.twilio.com/docs/sms/quickstart/csharp-dotnet-framework#receive-and-reply-to-inbound-sms-messages-with-aspnet-mvc.

All I have set is the Callback URL when sending the SMS message.  Everything appears to be "hooked up" correctly as I am receiving the MessageSID and Status, but there is no "Body" property.  Should there be??  As I read the example, it appears to be expecting a value for Body property.  Do I need to do something to set that property??

**Comment by BumpaRoy** [comment]
Update:

I think I was confusing two examples.  It is working now that I send the initial msg from my phone.  I was trying to send a message via a program to my twilio phone, then having twilio automatically send me back the status.  When I send it by my phone it is working.  Thank you.

**Comment by Swimburger** [comment]
Ah I see. Yes, the `Body` property is only for incoming SMS, not for status updates for outgoing SMS. 
This issue can be closed I think.

**Comment by Swimburger** [comment]
@dprothero can we close this?
