### ISSUE TITLE
Outdated Vulnerable transitive package

### ISSUE THREAD

**Issue by MostHostLA** [twilio-labs/twilio-aspnet#138]
There is a vulnerable package in the latest nuget:

System.Formats.Asn1 5.0.0 - current version is 8.0.1

Twilio (6.24)
> System.IdentityModel.Token.Jwt (6.35.0)
> \>Microsoft.IdentityModel.Tokens (6.35.0)
> \>System.Security.Cryptography.Cng (5.0.0)
> \>System.Formats.Asn1 (5.0.0)

I'm sure there is a way I can force this locally by changing the nuget package, but I and anyone using Nuget would really love it if the repo could get updated so as to use a non vulnerable package.

Version 5.0.0 seems to be the first ever, so I'm guessing this has just completely been ignored since the initial setup.

**Comment by AJLange** [comment]
Updated this repo to use Twilio 7.7 instead of 6.2.4
If there's a vulnerability still in 7.7 we'll push this problem up the chain.
