### ISSUE TITLE
Plans on replacing Newtonsoft by STJ

### ISSUE THREAD

**Issue by angelaki** [twilio-labs/twilio-aspnet#143]
Hey team,

any plans on replacing Newtonsoft.JSON by .Net's own STJ? Suffering pretty much on many of my references depending on this library.

**Comment by Swimburger** [comment]
Unfortunately, that's a dependency by the Twilio C# library, not the Twilio.AspNet library.
A lot of folks have asked for this but not much movement from Twilio.
https://github.com/twilio/twilio-csharp/issues/630

**Comment by angelaki** [comment]
Thank you! Gabe it a thumb up 👍
