### ISSUE TITLE
Queue Parameters missing from VoiceRequest

### ISSUE THREAD

**Issue by brcpar** [twilio-labs/twilio-aspnet#23]
None of the request classes have parameters such as QueueTime, QueueSid, QueueResult, QueuePosition, CurrentQueueSize, AvgQueueTimeOn which are used in callbacks from the waitUrl and action for the Enqueue verb.  The current workaround would be to create a class myself that inherits from VoiceRequest and include these, but it seems like they should be included in VoiceRequest class itself.

**Comment by chriswelles** [comment]
Missing AnsweredBy, etc as well.  Would be helpful if we didn't need to make our own class.

**Comment by dfjacobs** [comment]
Also missing ParentCallSid.  I'll create a pull request with the updated VoiceRequest, but I see no signs that anyone at Twilio has worked on this repo in the past year. This means that an updated VoiceRequest won't get into the nuget package until Twilio builds a new package.  Opened a support ticket at Twilio to try to get something going here, obviously no one at Twilio is monitoring the repo comments.

**Comment by dprothero** [comment]
@dfjacobs I would love a PR and would be happy to publish a new package.

And, yes, I totally dropped the ball on monitoring this repo's comments. 👎

**Comment by dfjacobs** [comment]
Great! I'll get something out by next week.

**Comment by dprothero** [comment]
Closing for now as there is a workaround. Happy to reopen should demand still be there.
