### ISSUE TITLE
Redirect SMS Response to another mobile number as SMS

### ISSUE THREAD

**Issue by djaus2** [twilio-labs/twilio-aspnet#30]
By default, the SMS reply with TwilioML is back to the sender.
I have found that an empty reply isn't sent back .. good.
Is there a simple way to change the reply to number?

I'm using code similar to that under **_Incoming SMS_** on this repository's **README**.

My context is a Blazor Server Controller Post handler.
My repository: [https://github.com/djaus2/MessagingBlazor](https://github.com/djaus2/MessagingBlazor)

**Comment by djaus2** [comment]
Yes I could add code similar to the Twilio Console app in my repository to send the message to the third party, but it seems limiting to not be able to change the reply to number.

**Comment by dprothero** [comment]
Just send an empty reply and use the [Twilio REST API](https://www.twilio.com/docs/sms/send-messages) to send the SMS to the other mobile number.

**Comment by Swimburger** [comment]
Not sure if this was available at the time, but now, alternatively, you can specify the `to` parameter:
```csharp
var response = new MessagingResponse();
response.Message("Send SMS to another number", to: "+1123456789");
response.Message("Respond to sender");
return response;
```
When you don't specify the `to` parameter, it'll default to respond to the sender.
