### ISSUE TITLE
Add TwiML extension methods

### ISSUE THREAD

**Issue by Swimburger** [twilio-labs/twilio-aspnet#41]
I'm not sure what the best practices are around extending controllers as libraries. If there are some good open-source repos that we could take a look at, that would be helpful.

I was wondering if, in addition to letting consumers inherit from `TwilioController` and using the inherited `TwiML` methods, if we could add extension methods to the `ControllerBase` class.
The benefit of this would be that consumers who already have their controller inherit from a different class, can also use the same `TwiML` method, without having to switch base class.

Looking for feedback on this one!

**Comment by dprothero** [comment]
@Swimburger that's a great idea. I think the original idea behind `TwilioController` came from the original library which was built before extension methods were a thing in C#.

**Comment by Swimburger** [comment]
Extension methods added in PR #45

**Comment by Swimburger** [comment]
PR Merged and will be released in an upcoming update 👏
