### ISSUE TITLE
Error 500 cannot load API for Swagger

### ISSUE THREAD

**Issue by twalbers** [twilio-labs/twilio-aspnet#47]
Visual Studio 2022 ASP.NET Core Web API.   When using 5.71 Swagger has an error 500 and will not load swagger.json. 
The error received is:  Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0
I am unsure how to fix this but if I revert back to 5.68.3 it works fine.  I am unsure what else you may need to know.  
Currently the API is essentially like the one out of the box in Visual Studio.

**Comment by Swimburger** [comment]
Hi @twalbers, I'm sorry you're running into this issue. I caused this bug and also fixed it, see #40.
Please stick to the previous version until next release, which will have the fix.

**Comment by twalbers** [comment]
Thanks for the quick response.  I will continue using 5.68.3 until the next release.

**Comment by Swimburger** [comment]
@twalbers 5.73.0 is released today and should contain the fix for your issue
