### ISSUE TITLE
Breaking changes moving from to 5.73.0 -> 5.77.0 

### ISSUE THREAD

**Issue by bwinklesky** [twilio-labs/twilio-aspnet#82]
Hi-

I upgraded to 5.77.0 from 5.73.0, and it seems to be breaking other libraries or at least modifying something that doesn't work with other libraries.  Not sure what changed in that release that would affect other libs.  

This update breaks Apple Sign In using OAuth 2 using the AspNet.Security.OAuth.Apple nuget package.  For whatever reason it seems to be hijacking the http client when making a token request and Apple is returning "invalid_client".  It's easy to reproduce by using 5.77.0 and integrating apple authorization.

**Comment by Swimburger** [comment]
Strange, we don't have that as a dependency in the project.
We did upgrade `Microsoft.AspNetCore.Mvc.Core` because the dependant `Microsoft.AspNetCore.Http` package had a security vulnerability. This is only for the .NET Standard 2.0 build.
If you are using .NET 5 or 6, it now doesn't have the `Microsoft.AspNetCore.Mvc.Core` dependency anymore, and relies on a framework dependency instead.

This change was made for #70.

This dependency change may be what triggered your issue, but there is probably a better way to fix it and still use the patched `Microsoft.AspNetCore.Http` package.

**Comment by bwinklesky** [comment]
Definitely not something I expected when the error started showing up on my applications.  I spent several hours in a process of elimination and didn’t even think it would break something so disconnected.  I’m using net6.0 and not really clear on what is going on.  Based on the error my guess is it’s changing http request header to be “application/json” for the content type and Apple is expecting form encoding.  I could be wrong…



From: Niels Swimberghe ***@***.***>
Date: Wednesday, August 3, 2022 at 11:55 AM
To: twilio-labs/twilio-aspnet ***@***.***>
Cc: Brett Winklesky ***@***.***>, Author ***@***.***>
Subject: Re: [twilio-labs/twilio-aspnet] Breaking changes moving from to 5.73.0 -> 5.77.0 (Issue #82)

Strange, we don't have that as a dependency in the project.
We did upgrade Microsoft.AspNetCore.Mvc.Core because the dependant Microsoft.AspNetCore.Http package had a security vulnerability. This is only for the .NET Standard 2.0 build.
If you are using .NET 5 or 6, it now doesn't have the Microsoft.AspNetCore.Mvc.Core dependency anymore, and relies on a framework dependency instead.

This change was made for #70<https://github.com/twilio-labs/twilio-aspnet/issues/70>.

This dependency change may be what triggered your issue, but there is probably a better way to fix it and still use the patched Microsoft.AspNetCore.Http package.

**Comment by Swimburger** [comment]
@bwinklesky have you found a solution?
I do think the Twilio SDK which Twilio.AspNet depends on has also received some updates. The Twilio SDK has a dependency on `System.IdentityModel.Tokens.Jwt` which may influence your Apple Auth? I personally wouldn't know.

**Comment by Swimburger** [comment]
Closing this for now. We can reopen this if necessary.

**Comment by bwinklesky** [comment]
I tested 6.0 and the issue is still present.  I'm going to need to stay on 5.73 until the issue is resolved in the Twilio SDK.

**Comment by Swimburger** [comment]
@bwinklesky are you able to reproduce the issue when not using `Twilio.AspNet` but still using `Twilio`?

**Comment by bwinklesky** [comment]
I added Twilio 5.79.0 along with Twilio.AspNet.Core 5.73.0 and that creates the invalid_client error from Apple.  I will try other versions to see if there's a version that works.

**Comment by bwinklesky** [comment]
The breaking change is in version 5.76.0.  I went back to Twilio 5.73 and worked my way up.

**Comment by Swimburger** [comment]
I'm wondering it's reproducible when you remove `Twilio.AspNet.Core` and add `Twilio`.

**Comment by bwinklesky** [comment]
I removed Twilio.AspNet.Core and added Twilio 5.76.0.  The issue still exists.

**Comment by Swimburger** [comment]
So it must be caused by the `Twilio` transitive dependencies. I happen to find the following issue which was fixed a couple months ago: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1861
I hope there's some information in there that can help you get this fixed!

**Comment by bwinklesky** [comment]
You should make the minimum version be 6.20.0 for System.IdentityModel.Tokens.Jwt.  I added that version and the issue is resoled.

**Comment by Swimburger** [comment]
Fantastic! I'm glad it fixed your issue.
Let me create an issue for the `Twilio` library so they can update that version.
